<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends EntityRepository
{
    /**
     * @param int $amount
     * @return Product[]
     */
    public function getRandomWords($amount = 10)
    {
        return $this->getRandomWordsNativeQuery($amount)->getResult();
    }

    /**
     * @param int $amount
     * @return ORM\NativeQuery
     */
    public function getRandomWordsNativeQuery($amount = 10)
    {
        $table = $this->getClassMetadata()
            ->getTableName();

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult($this->getEntityName(), 'w');
        $rsm->addFieldResult('w', 'id', 'id');
        $rsm->addFieldResult('w', 'original', 'original');
        $rsm->addFieldResult('w', 'foreign', 'foreign');

        return $this->getEntityManager()
            ->createNativeQuery("
                SELECT w.* FROM {$table} w WHERE w.collection_id = 1 ORDER BY RAND() LIMIT 0, {$amount}", $rsm);
    }
}
